import { Improvement } from "../../Models/Improvement";
import { Tile } from "../Tile/Tile";
import "./Map.css";

export function Map(props: { resources: any; improvements: Improvement[] }) {
  return (
    <div className="mapGrid">
      <Tile
        resources={props.resources}
        improvements={props.improvements}
      ></Tile>
      <Tile
        resources={props.resources}
        improvements={props.improvements}
      ></Tile>
      <Tile
        resources={props.resources}
        improvements={props.improvements}
      ></Tile>
      <Tile
        resources={props.resources}
        improvements={props.improvements}
      ></Tile>
      <Tile
        resources={props.resources}
        improvements={props.improvements}
      ></Tile>
      <Tile
        resources={props.resources}
        improvements={props.improvements}
      ></Tile>
      <Tile
        resources={props.resources}
        improvements={props.improvements}
      ></Tile>
      <Tile
        resources={props.resources}
        improvements={props.improvements}
      ></Tile>
      <Tile
        resources={props.resources}
        improvements={props.improvements}
      ></Tile>
      <Tile
        resources={props.resources}
        improvements={props.improvements}
      ></Tile>
      <Tile
        resources={props.resources}
        improvements={props.improvements}
      ></Tile>
      <Tile
        resources={props.resources}
        improvements={props.improvements}
      ></Tile>
      <Tile
        resources={props.resources}
        improvements={props.improvements}
      ></Tile>
      <Tile
        resources={props.resources}
        improvements={props.improvements}
      ></Tile>
      <Tile
        resources={props.resources}
        improvements={props.improvements}
      ></Tile>
      <Tile
        resources={props.resources}
        improvements={props.improvements}
      ></Tile>
      <Tile
        resources={props.resources}
        improvements={props.improvements}
      ></Tile>
      <Tile
        resources={props.resources}
        improvements={props.improvements}
      ></Tile>
      <Tile
        resources={props.resources}
        improvements={props.improvements}
      ></Tile>
      <Tile
        resources={props.resources}
        improvements={props.improvements}
      ></Tile>
      <Tile
        resources={props.resources}
        improvements={props.improvements}
      ></Tile>
      <Tile
        resources={props.resources}
        improvements={props.improvements}
      ></Tile>
      <Tile
        resources={props.resources}
        improvements={props.improvements}
      ></Tile>
      <Tile
        resources={props.resources}
        improvements={props.improvements}
      ></Tile>
      <Tile
        resources={props.resources}
        improvements={props.improvements}
      ></Tile>
    </div>
  );
}
